[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38', 'py39']
preview=true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | __pycache__
  | _build
  | buck-out
  | build
  | dist
)/
'''
[tool.isort]
atomic = true
profile = "black"
line_length = 120
skip_gitignore = true
